# Generated by Django 3.2.9 on 2022-01-17 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0005_addressmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressmodel',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='addressmodel',
            old_name='l_name',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='address',
            field=models.CharField(max_length=300),
        ),
    ]
