# Generated by Django 3.2.9 on 2022-01-18 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0006_auto_20220117_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placeorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('ORDERPLACED', 'ORDERPLACED'), ('ON THE WAY', 'ON THE WAY'), ('SHIPPED', 'SHIPPED'), ('OUT FOR DELIVERY', 'OUT FOR DELIVERY'), ('CANCEL', 'CANCEL')], default='PENDING..', max_length=20)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.addressmodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.productmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
