# Generated by Django 3.2.9 on 2022-02-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_placeorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeorder',
            name='status',
            field=models.CharField(choices=[('ORDERPLACED', 'ORDERPLACED'), ('SHIPPED', 'SHIPPED'), ('ON THE WAY', 'ON THE WAY'), ('OUT FOR DELIVERY', 'OUT FOR DELIVERY'), ('CANCELLLED', 'CANCELLED')], default='PENDING..', max_length=20),
        ),
    ]
